language: go
python: '1.13'
env:
  global:
    secure: HkeZi4jaS8D43EAIjb5XoiQZXSZlLJ92tZ+TKPS267JELeqznFyCsIlBAkh2VQiI2996vjYm1vZ2BamHdoud5ulQCp8NLALtVs28ZTjbuH3vOaHqNwMzTCv1xUyR2d+qjMruTD94Z34MV/q4Ix7Lem4iWQ8DMNdc7A/nf1wKXtgXP15G2+FH6ST4dt8mm2hv1mCMx7+5JzveDAjnsNfVoI2gR9IJw/fMdvS6uu0eE+2Q5HYLfFpCuhxAZ8NMHB458iNIPYd69ZrUqQKS/CyREWd+cMRvTl8LAXq1AcKj7K3c2hPJvMp+lxVN6AwzT3tM9aDZFBfgYlh/RlvpacB8+8dSWicUjWEEh7d029jreiOrmx8I8yYHQBej+ehFwYPXOUMsG3ZlmP7OyaURqUHesgD6rcSsr6GYHNAlQaq0SbXdCfj5g8p7a0PMWUxytsT9oSPaHrhobHgWrDm9yv09NE1O5/DlgiZLdp2wrQC1GxKRI4cSzJ/vRnPdmM/i/SaNT6zkz/cpQ8hKaVV/x1Awsq0NmnzpSh5SU2mRpVtNlFBr0wvMORutYP8DTRcZbjIop11tYT2TVvp/QsHDL5F+l2aTVbaCOlEbDoIMCImqCho6E8tGNx+aXniswt5rqzDA07HtDfN3fmhQKZ0cGiIqCDXVzlKAXIdDcSmiJTLcnjc=
jobs:
  include:
  - stage: test
    script:
    - echo No Tests Exist...
  - stage: deploy
    if: branch = master AND (NOT type IN (pull_request))
    before_install:
    - npm i -g npm@6.6.0
    script:
    - npm install @semantic-release/exec
    - npx semantic-release
