language: go
go: '1.13'
env:
  global:
    secure: G9N/ZCOUBDli7V1WmCi31SSKdoB0ezgES+NlCDp5+SUCwTJpGkdpbHpTocp/dOWIOdDk++w07NlTErqzO6zVqcuJlkO8SbUmnu7mzy3Lhi6XUgNruc+CcbrpR+yNSMLJmMy1X/i9PO3mJVXb52C8ZkN5pgZqdTtSarRE1SMLm9bk2p56f5kjUvxilwAcacC15GcDH07SlsskDClputYZgwZvGhOQ4fhXPGUc+ZEmdZ8+2LgEsof5sDM4nqV9EFhrqt3E+ecK0/fVl8s7o4HO7vHHTr+p65FcxqoRuYCIinBejpbNynxE+ANBfkanFAnoW5Ru+jCPl8s6Afu0ye4tPNPO7+v2Vo3aThAlSDGTef18eGaO5J4xD2ICMBPq7ohrb/KRzcsiWHkG5QgkQfSyPNkRzzeEgnTnA/gQ/w64CyqmTsiPsTdf7B7BBAdIuxCXK6nmlbFet6n36rKhAjgLOE1x4DqjkiZ+kNBqv8N/PYj4WaaQsOLt3zMPk+kVhBKT2tzwY2Vjvcd6yv5SKMIXBO41ZKa8Nq6E19aEwzygxCxEBly/wDwh7jKV4OePh+6VbP1D/LPT4wqZR4fAL3nnYFk+0v62suDYB5EkcLfPd31NiBZzT9vV+sTn8qnWXJhJYzxdj4xu32NAie5E5JqsduuJkznkFzAso0NjrybGgRg=
jobs:
  include:
  - stage: test
    script:
    - echo No Tests Exist...
  - stage: deploy
    if: branch = master AND (NOT type IN (pull_request))
    before_install:
    - npm i -g npm@6.6.0
    script:
    - npm install @semantic-release/exec
    - npx semantic-release
